apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tests.bink.com
spec:
  scope: Namespaced
  names:
    kind: StarbugTest
    plural: tests
    singular: test
    shortNames:
    - test
  group: bink.com
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          description: The status of the test
          jsonPath: .status.status
        - name: Results
          type: string
          description: The results of the test
          jsonPath: .status.results
        - name: Age
          type: date
          description: The age of the test
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              default: {}
              properties:
                status:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Completed
                    - Failed
                  default: Pending
                results:
                  type: string
            spec:
              type: object
              properties:
                infrastructure:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                applications:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                test:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
