apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &id001
    app: postgres
  name: postgres
  namespace: starbug
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: postgres
      labels: *id001
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_MULTIPLE_DATABASES
          value: europa,hades,vela,harmonia,hermes,hubble,api_reflector,zagreus,atlas,midas,carina,copybot,cosmos,momus,eos,polaris,bullsquid,pontus,snowstorm,thanatos,prefect,kiroshi
        image: docker.io/postgres:15
        name: postgres
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: init-script
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: spot
      serviceAccountName: postgres
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      volumes:
      - configMap:
          name: postgres-init-script
        name: init-script
