apiVersion: bink.com/v1
kind: StarbugTest
metadata:
  name: ait-big-gray-rabbit
  namespace: starbug
spec:
  infrastructure:
    - name: postgres
  applications:
    - name: kiroshi
  test:
    name: kiroshi
