[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "starbug"
version = "0.0.0"
description = "Test Automation API"
authors = ["Chris Pressland <mail@cpressland.io>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "./starbug"},
    {include = "./scutter"},
]

[tool.poetry.scripts]
starbug = "starbug.cli:cli"
scutter = "scutter.cli:cli"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
fastapi = "^0.103.2"
click = "^8.1.7"
click-aliases = "^1.0.2"
uvicorn = "^0.23.2"
requests = "^2.31.0"
loguru = "^0.7.2"
azure-storage-blob = "^12.18.3"
azure-identity = "^1.14.1"
azure-mgmt-msi = "^7.0.0"
pendulum = "^2.1.2"
kr8s = "^0.9.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.0"
black = "^23.9.1"
refurb = "^1.21.0"

[tool.black]
line-length = 120

[tool.ruff]
select = ["ALL"]
ignore = ["ANN101", "D203", "D213", "D407", "FA102", "PERF203", "PLR0913", "S108", "S311"]
line-length = 250
