[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "starbug"
version = "0.0.0"
description = "Test Automation API"
authors = ["Chris Pressland <mail@cpressland.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
starbug = "starbug.cli:cli"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
pydantic = "^2.0.2"
kubernetes = "^26.1.0"
click = "^8.1.4"
uvicorn = "^0.22.0"
requests = "^2.31.0"
pendulum = "^2.1.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.278"
black = "^23.7.0"

[tool.black]
line-length = 120

[tool.ruff]
select = ["ALL"]
ignore = ["D203", "D213", "D407", "ANN101", "PLR0913"]
line-length = 250
