[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "starbug"
version = "0.0.0"
description = "Test Automation API"
authors = ["Chris Pressland <mail@cpressland.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
starbug = "starbug.cli:cli"
scutter = "scutter.cli:cli"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
pydantic = "^2.0.2"
kubernetes = "^26.1.0"
click = "^8.1.4"
uvicorn = "^0.22.0"
requests = "^2.31.0"
pendulum = "^2.1.2"
tabulate = "^0.9.0"
click-aliases = "^1.0.1"
inotify = "^0.2.10"
azure-storage-blob = "^12.17.0"
loguru = "^0.7.2"
pydantic-settings = "^2.0.3"
sqlalchemy = "^2.0.20"
psycopg = "^3.1.10"
alembic = "^1.12.0"
kr8s = "^0.8.17"
rq = "^1.15.1"
azure-identity = "^1.14.0"
azure-mgmt-msi = "^7.0.0"
randomname = "^0.2.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.278"
black = "^23.7.0"
refurb = "^1.21.0"

[tool.black]
line-length = 120

[tool.ruff]
select = ["ALL"]
ignore = ["D203", "D213", "D407", "ANN101", "PLR0913", "PERF203", "S311"]
line-length = 250
